//! Rendering of the container's `/etc/hosts`.
//!
//! The file is generated from the same validated addresses that were installed
//! in the firewall, so the container can never learn an address the firewall
//! does not allow (and vice versa). It is written atomically into a directory
//! that is bind-mounted read-only into the searcher container, where
//! `/etc/hosts` is a symlink to it.

use crate::config::StaticHost;
use crate::plan::NameState;

pub fn render(static_hosts: &[StaticHost], names: &[NameState]) -> String {
    let mut s = String::new();
    s.push_str("# Generated by egress-resolver from the attested endpoint list; do not edit.\n");
    s.push_str("# Names below resolve only to addresses currently allowed by the host firewall.\n");
    s.push_str("127.0.0.1 localhost\n");
    if !static_hosts.is_empty() {
        s.push_str("\n# static endpoints\n");
        for sh in static_hosts {
            s.push_str(&format!("{} {}\n", sh.ip, sh.names.join(" ")));
        }
    }
    if !names.is_empty() {
        s.push_str("\n# dynamically resolved endpoints\n");
        for n in names {
            if n.addrs.is_empty() {
                s.push_str(&format!("# {}: no address ({:?})\n", n.name, n.source));
                continue;
            }
            for ip in &n.addrs {
                s.push_str(&format!("{ip} {}\n", n.name));
            }
        }
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::answers::Outcome;
    use crate::plan::Source;
    use std::net::Ipv4Addr;

    fn ip(s: &str) -> Ipv4Addr {
        s.parse().unwrap()
    }

    #[test]
    fn renders_static_then_dynamic_in_order() {
        let statics = vec![
            StaticHost {
                ip: ip("3.149.14.12"),
                names: vec!["tx.tee-searcher.flashbots.net".into()],
            },
            StaticHost {
                ip: ip("18.221.59.61"),
                names: vec!["backruns.tee-searcher.flashbots.net".into()],
            },
        ];
        let names = vec![
            NameState {
                name: "rpc.buildernet.org".into(),
                required: true,
                outcome: Outcome::Ok,
                source: Source::Fresh,
                addrs: vec![ip("200.225.47.181"), ip("200.225.47.183")],
                error: None,
            },
            NameState {
                name: "direct-ap.buildernet.org".into(),
                required: false,
                outcome: Outcome::Transient,
                source: Source::Missing,
                addrs: vec![],
                error: Some("SERVFAIL".into()),
            },
        ];
        let out = render(&statics, &names);
        let lines: Vec<&str> = out.lines().filter(|l| !l.starts_with('#') && !l.is_empty()).collect();
        assert_eq!(
            lines,
            vec![
                "127.0.0.1 localhost",
                "3.149.14.12 tx.tee-searcher.flashbots.net",
                "18.221.59.61 backruns.tee-searcher.flashbots.net",
                "200.225.47.181 rpc.buildernet.org",
                "200.225.47.183 rpc.buildernet.org",
            ]
        );
        assert!(out.contains("# direct-ap.buildernet.org: no address"));
    }
}
